GET https://localhost:7292/Question/GetOptions?id=1
Accept: application/json

###
GET https://localhost:7292/api/Questions/1/Options
Accept: application/json

###
PUT https://localhost:7292/api/Questions/8/Title
Content-Type: application/json

"random title"

###
PUT https://localhost:7292/api/Questions/8/Option
Content-Type: application/json

"option 4"

###
PUT https://localhost:7292/api/Flows
Content-Type: application/json

{
  "id": "1",
  "NewName": "test",
  "NewDescription": "test"
}


###
GET https://localhost:7292/api/Flows/1
Accept: application/json